CREATE TABLE temps (
    id INT NOT NULL AUTO_INCREMENT,
    timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    layer ENUM('PRESENTATION', 'BUSINESS', 'PERSISTENCE', 'DATABASE') NOT NULL,
    log_type ENUM('REQUEST', 'RESPONSE') NOT NULL,
    correlation_id VARCHAR(255) NOT NULL,
    status VARCHAR(255) DEFAULT NULL,
    msg VARCHAR(255) DEFAULT NULL,
    error JSON DEFAULT NULL,
    data JSON DEFAULT NULL,
    PRIMARY KEY (id),
    INDEX idx_correlation_id (correlation_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
