name: pytest docker compose

on:
    push:
      branches: [ main, chore/setup-cicd ]
    pull_request:
      branches: [ main ]

jobs:
  test:
    if: github.actor == github.repository_owner
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate .env file
        run: |
          echo "MYSQL_ROOT_PW=${{ secrets.MYSQL_ROOT_PW }}" >> .env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
          echo "DB_USER=${{ secrets.DB_USER }}" >> .env
          echo "DB_PW=${{ secrets.DB_PW }}" >> .env
          echo "DB_PORT=${{ secrets.DB_PORT || '3306' }}" >> .env
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "DEEPL_AUTH_KEY=${{ secrets.DEEPL_AUTH_KEY }}" >> .env
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env

      - name: Build and run containers
        run: docker compose up -d --build


      
      - name: Wait for DB to be ready
        run: sleep 30

      - name: Run sample test1
        run: docker exec fastapi_server pytest tests/test_sample1.py --cov=. --cov-report=term-missing -s

      - name: Run sample test2
        run: docker exec fastapi_server pytest tests/test_sample2.py --cov=. --cov-report=term-missing -s

      # - name: Run tests inside fastapi container
      #   run: |
      #     docker exec -e RUN_INTEGRATION=true fastapi_server \
      #       pytest tests/ -s --cov=app --cov-report=term-missing

      - name: Generate HTML coverage report
        run: |
          docker exec -e RUN_INTEGRATION=true fastapi_server \
            pytest tests/ -s --cov=app --cov-report=html
          docker cp fastapi_server:/app/htmlcov ./htmlcov

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: htmlcov

      - name: Tear down
        if: always()
        run: docker compose --env-file /dev/null down